export const GEO_PARSER_ERROR_CODES = {
  SHAPEFILE_MISSING_CORE_FILES: 'SHAPEFILE_MISSING_CORE_FILES',
  SHAPEFILE_MISSING_PRJ_FILE: 'SHAPEFILE_MISSING_PRJ_FILE',
  SHAPEFILE_PRJ_FILE_TOO_LARGE: 'SHAPEFILE_PRJ_FILE_TOO_LARGE',
  SHAPEFILE_NOT_FOUND: 'SHAPEFILE_NOT_FOUND',
  ZIP_TOO_MANY_FILES: 'ZIP_TOO_MANY_FILES',
  ZIP_TOO_LARGE: 'ZIP_TOO_LARGE',
  ZIP_COMPRESSION_SUSPICIOUS: 'ZIP_COMPRESSION_SUSPICIOUS',
  COORDINATES_INVALID_LONGITUDE: 'COORDINATES_INVALID_LONGITUDE',
  COORDINATES_INVALID_LATITUDE: 'COORDINATES_INVALID_LATITUDE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE'
}

export const isGeoParserErrorCode = (code) => {
  return Object.values(GEO_PARSER_ERROR_CODES).includes(code)
}
