export const EXEMPTION_STATUS = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  SUBMITTED: 'SUBMITTED',
  WITHDRAWN: 'WITHDRAWN'
}

export const EXEMPTION_STATUS_LABEL = {
  DRAFT: 'Draft',
  SCHEDULED: 'Scheduled',
  ACTIVE: 'Active',
  EXPIRED: 'Expired',
  Closed: 'Active',
  SUBMITTED: 'Submitted',
  WITHDRAWN: 'Withdrawn'
}

export const SUBMITTED_STATUSES = [
  EXEMPTION_STATUS.SCHEDULED,
  EXEMPTION_STATUS.ACTIVE,
  EXEMPTION_STATUS.EXPIRED
]

export const WITHDRAWABLE_STATUSES = [
  EXEMPTION_STATUS.SCHEDULED,
  EXEMPTION_STATUS.ACTIVE
]

export const EXEMPTION_TYPE = {
  EXEMPT_ACTIVITY: 'EXEMPT_ACTIVITY'
}
